function (target_set_warnings _target)
    if (NOT WARNINGS_DISABLED)
        set (WARNINGS_FLAGS -Wall -Wextra -Wpedantic)
        set (WARNINGS ${WARNINGS_FLAGS} -Werror)
        target_compile_options (${_target} PRIVATE ${WARNINGS})
        message (
            STATUS "Compile ${_target} with the following warnings ${WARNINGS}")
    else ()
        message (STATUS "Compile ${_target} without compiler warnings!")
    endif ()
endfunction ()
